######################################################################
# Automatically generated by qmake (1.07a) Mon May 23 15:10:08 2005
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += netchatserver.cpp ../lib/buddylist.cpp ../lib/buddy.cpp
